export const ROUTES = {
  DASHBOARD: {
    MAIN: 'Main',
    HOME: 'HomeScreen',
    INTRO: 'IntroductionScreen',
    CARD: 'CardScreen',
    INVESTMENT: 'InvestmentScreen',
    LOAN: 'LoanScreen',
    VIKKI_TIPS: 'VikkiTipsScreen',
    PROFILE_DASHBOARD: 'ProfileDashboard',
    PROFILE_DETAILS: 'PROFILE_DETAILS',
    LOYALTY: 'LoyaltyScreen',
    VIKKI_CONTENT_SCREEN: 'VikkiContentScreen',
    VIKKI_CONTENT_DETAIL_SCREEN: 'VikkiContentDetailScreen',
    CHANGE_WALLPAPER_SCREEN: 'ChangeWallpaperScreen',
    VIKKI_PARTNERS_SCREEN: 'VikkiPartnersScreen',
    PROFILE_INFORMATION_EXPIRED_SCREEN: 'ProfileInformationExpiredScreen',
    VERIFIED_IDENTITY_INFO_SCREEN: 'VerifiedIdentityInfoScreen',
    NFC_SCANNING_SCREEN: 'NFCScanningScreen',
    DOC_SCANNING_SCREEN: 'DocScanningScreen',
    DOC_UNCLEAR_SCREEN: 'DocUnclearScreen',
    FACE_CAPTURE_SCREEN: 'FaceCaptureScreen',
    FACE_UNCLEAR_SCREEN: 'FaceUnclearScreen',
    UPDATE_IDENTITY_INFO_INSTRUCTION_SCREEN:
      'UpdateIdentityInfoInstructionScreen',
  },
  LENDING: {
    PRODUCT_INTRODUCTION: 'ProductIntroductionScreen',
  },
  CARDS: {
    CARDS_SCREEN: 'CardsScreen',
    CARD_DETAILS_SCREEN: 'CardDetailsScreen',
    CARD_DETAILS_MODAL_SCREEN: 'CardDetailsModalScreen',
    MANAGE_CARDS: 'ManageCards',
    CARD_MANAGE_LIMIT: 'CardManageLimit',
    MORE_SETTINGS: 'MoreSettingsScreen',
    CARD_REPLACEMENT_REASON: 'CardReplacementReasonScreen',
    CARD_INTRO: 'CardIntroScreen',
    CARD_REPLACEMENT_CONFIRM: 'CardReplacementConfirmScreen',
    CARD_DAILY_LIMIT_SETTING: 'CardDailyLimitSettingScreen',
    CARD_DETAILS_WITH_TRANSACTIONS: 'CardDetailWithTransactionsList',
    CARD_TOP_UP: 'CardTopupScreen',
    CARD_TOP_UP_CONFIRM: 'CardTopupConfirmScreen',
    CARD_TOP_UP_RESULT: 'CardTopupResultScreen',
    CARD_MANAGEMENT_SCREEN: 'CardManagementScreen',
    CARD_TRANSACTION_DETAILS: 'CardTransactionDetails',
  },
  PAYMENT: {
    CONFIRM_TRANSFER: 'ConfirmTransferScreen',
    CHOOSE_BANK: 'ChooseBank',
    INPUT_BANK_ACCOUNT: 'InputBankAccount',
    INPUT_TRANSFER_DETAIL: 'InputTransferDetail',
    INPUT_VIKKI_ACCOUNT: 'InputVikkiAccount',
    INPUT_ATM_CARD: 'InputATMCard',
    TRANSFER_DASHBOARD: 'TransferDashboard',
    TRANSFER_RESULT: 'TransferResult',
    ADD_MONEY: 'AddMoneyScreen',
    TOP_UP: 'TopUpScreen',
    FAVORITE_LIST: 'FavoriteListScreen',
    QR: 'QRScreen',
    MY_QR: 'MyQRScreen',
    VNPAY_QR_DETAILS: 'VNPayQRDetailsScreen',
    VNPAY_INPUT_DETAILS: 'InputVNPayTransferDetailScreen',
    BALANCE_DETAILS: 'BalanceDetails',
  },
  BILL_PAYMENT: {
    DASHBOARD: 'BillPaymentDashboardScreen',
    CHOOSE_PROVIDER: 'ChooseProvider',
    INPUT_CUSTOMER_ID: 'InputCustomerIdScreen',
    DETAIL: 'BillDetailScreen',
    CONFIRM_INFORMATION: 'BillInfoConfirmScreen',
    PAY_RESULT: 'BillPaymentResultScreen',
    SET_UP_AUTO_BILL: 'SetUpAutoBillScreen',
    SET_UP_AUTO_BILL_SUCCESS: 'SetUpAutoBillSuccessScreen',
    TRAFFIC_INPUT_CUSTOMER_ID: 'TrafficInputCustomerIdScreen',
    BILL_PAYMENT_HISTORY: 'BillPaymentHistoryScreen',
  },
  PAYROLL: {
    PAYROLL_DASHBOARD: 'PayrollDashBoard',
    PAYROLL_TRANSFER: 'PayrollTransfer',
    PAYROLL_CONFIRM_TRANSFER: 'PayrollConfirmTransfer',
    PAYROLL_TRANSFER_RESULT: 'PayrollTransferResult',
    PAYROLL_ACCOUNT_LIMIT: 'PayrollAccountLimit',
  },
  TRANSACTION: {
    TRANSACTIONS_SCREEN: 'TransactionsScreen',
    TRANSACTION_DETAIL_SCREEN: 'TransactionDetails',
    ACCOUNT_LIMIT_SCREEN: 'AccountLimitScreen',
    ACCOUNT_SET_DAILY_LIMIT_SCREEN: 'AccountSetDailyLimitScreen',
    DISPUTE_REASON_SCREEN: 'DisputeReasonScreen',
    REFUND_REQUEST_SCREEN: 'RefundRequestScreen',
    DISPUTE_DETAIL_SCREEN: 'DisputeDetailScreen',
  },
  SMART_OTP: {
    CREATE_SMART_OTP: 'CreateSmartOtp',
    CONFIRM_SMART_OTP: 'ConfirmSmartOtp',
  },
  NOTIFICATION: {
    NOTIFICATION_SCREEN: 'NotificationScreen',
    NOTIFICATION_SETTING_SCREEN: 'NotificationSettingScreen',
    NOTIFICATION_DETAIL_SCREEN: 'NotificationDetailScreen',
  },
  CUSTOMER_SERVICE: {
    CHAT_SCREEN: 'ChatScreen',
    VIRTUAL_ASSISTANT_SCREEN: 'VirtualAssistantScreen',
  },
  AUTH: {
    LOGIN_PHONE: 'LoginPhoneScreen',
    LOGIN_PASSWORD: 'LoginPasswordScreen',
    LOGIN_PIN: 'LoginPinScreen',
    FACE_AUTHENTICATION: 'FaceAuthenticationScreen',
    FACE_AUTH_RETRY: 'FaceAuthRetryScreen',
    CREATE_NEW_PASSWORD: 'CreateNewPasswordScreen',
    CREATE_NEW_PIN: 'CreateNewPinScreen',
    CONFIRM_NEW_PIN: 'ConfirmNewPinScreen',
    NFC_SCANNING: 'NFCScanningScreen',
  },
  COMMON: {
    STARTUP: 'StartupScreen',
    INFORMATION: 'InformationScreen',
    WEB_VIEW: 'WebViewScreen',
    VIKKIVERSE: 'VikkiverseScreen',
    ADDRESS_SELECT: 'AddressSelectScreen',
    VIDEO_INSTRUCTION: 'VideoInstructionScreen',
    PDF_REVIEW: 'PdfReviewScreen',
    MOCK_ACCOUNT: 'MockAccountScreen',
    MAINTENANCE: 'MaintenanceScreen',
    IMAGE_VIEW_MODAL_SCREEN: 'ImageViewModalScreen',
    HDBANK_BRANCH_SELECT: 'HDBankBranchSelect',
    QRCODE_SHARE: 'QRCodeShareScreen',
  },
  ONBOARD: {
    REGISTER_PHONE: 'RegisterPhoneScreen',
    DOC_REGISTRATION: 'DocRegistrationScreen',
    CUSTOMER_DETAIL: 'CustomerDetailScreen',
    FACE_REGISTRATION: 'FaceRegistrationScreen',
    CREATE_PASSWORD: 'CreatePasswordScreen',
    CREATE_PIN: 'CreatePinScreen',
    CONFIRM_PIN: 'ConfirmPinScreen',
    CONGRAT: 'CongratScreen',
    CONGRAT_WITH_CHECK_STATUS: 'CongratWithCheckStatusScreen',
    SELFIE_UNCLEAR: 'SelfieUnclearScreen',
    ID_SCAN_UNCLEAR: 'IDScanUnclearScreen',
    SJ_CONGRAT: 'SJCongratScreen',
    FIN_CONGRAT: 'FINCongratsScreen',
    PASSPORT_VERIFICATION: 'PassportVerificationScreen',
    NATIONALITY_SELECT: 'NationalityScreen',
    PASSPORT_DETAIL: 'PassportDetailScreen',
    VISA_INFO: 'VisaInfoScreen',
    OTHER_INFO: 'OtherInfoScreen',
    COMPLETE_PASSPORT: 'CompletePassportScreen',
    NFC_REGISTRATION: 'NfcRegistrationScreen',
    NFC_SCAN_ERROR: 'NfcScanErrorScreen',
  },
  HD_CREDIT_CARD: {
    PRODUCT_INTRODUCTION: 'HDProductIntroductionScreen',
    CONSENT_OTP_SCREEN: 'ConsentOTPScreen',
    LEAD_DETAIL: 'LeadDetailScreen',
    DOC_SCAN: 'DocumentScanScreen',
    PERSONAL_INFO: 'PersonalInformationScreen',
    WORK_INFO: 'WorkInformationScreen',
    DELIVERY_INFO: 'DeliveryInformationScreen',
    REVIEW_CONTRACT_SCREEN: 'ReviewContractScreen',
    APPLY_SUCCESS_SCREEN: 'ApplySuccessScreen',
    HD_ADDRESS_SELECT: 'HdAddressSelectScreen',
    CARD_APPROVED_SCREEN: 'CardApprovedScreen',
    REJECT_SCREEN: 'RejectScreen',
    CARD_REJECT_SCREEN: 'CardRejectScreen',
  },
  TERM_DEPOSIT: {
    TERM_SAVING_DASHBOARD: 'TermSavingDashboardScreen',
    DETAIL: 'TermDepositDetailScreen',
    CREATE: 'TermDepositCreateScreen',
    CONFIRMATION: 'TermDepositConfirmationScreen',
    PRODUCT_INTRO: 'TermDepositProductIntroScreen',
    CREATE_SUCCESS: 'TermDepositCreateSuccessScreen',
    WITHDRAW_SUCCESS: 'TermDepositWithdrawSuccessScreen',
    WITHDRAW_CONFIRMATION: 'TermDepositWithdrawConfirmationScreen',
    PARTIAL_WITHDRAW: 'TermDepositPartialWithdrawScreen',
    CLOSED_LIST: 'TermDepositClosedScreen',
  },
  PHONE_TOP_UP: {
    DASHBOARD: 'PhoneTopUpDashboardScreen',
    CONFIRM_INFORMATION: 'PhoneTopUpConfirmScreen',
    RESULT: 'PhoneTopUpResultScreen',
  },
  CREDIT_CARD: {
    CARD_IN_REVIEW: 'CreditCardInReviewScreen',
    CARD_REJECT: 'CreditCardRejectScreen',
    CARD_APPROVED: 'CreditCardApprovedScreen',
    CARD_DASHBOARD: 'CreditCardDashboardScreen',
    CARD_READY: 'CreditCardReadyForPaymentScreen',
    CARD_DETAILS_MODAL: 'CreditCardDetailsModalScreen',
    INPUT_REPAYMENT_SCREEN: 'CreditCardInputRepaymentScreen',
    REVIEW_REPAYMENT_SCREEN: 'CreditCardReviewPaymentScreen',
    REPAYMENT_RESULT_SCREEN: 'CreditCardPaymentResultScreen',
    STATEMENT_LIST_SCREEN: 'StatementsListScreen',
    STATEMENT_DETAIL_SCREEN: 'StatementsDetailScreen',
    STATEMENT_HISTORY_SCREEN: 'StatementsHistoryScreen',
    MANAGEMENT_SCREEN: 'CreditCardManagementScreen',
    REFERENCE_INFO_SCREEN: 'CreditCardReferenceInfoScreen',
    SELFIE_SCREEN: 'CreditCardSelfieScreen',
    ACCOUNT_DETAIL: 'CreditCardAccountDetailScreen',
    TRANSACTION_DETAIL: 'CreditCardTransactionDetailScreen',
    SELECT_CARD_TYPE: 'CreditCardSelectType',
    INSTALMENT_SCREEN: 'InstalmentScreen',
    INSTALMENT_OFFER_SCREEN: 'InstalmentOfferScreen',
    CONFIRM_CONVERT_INSTALMENT_SCREEN: 'ConfirmConvertInstalmentScreen',
    INSTALMENT_DETAILS_SCREEN: 'InstalmentDetailScreen',
    CREDIT_CARD_NFC_GUIDE: 'CreditCardNFCGuide',
    SUCCESS_SCREEN: 'SuccessScreen',
  },
  STATEMENT: {
    STATEMENT_DATE_RANGE_SCREEN: 'StatementDateRangeScreen',
    STATEMENT_SCREEN: 'StatementScreen',
    STATEMENT_REASON_SCREEN: 'StatementReasonScreen',
    CONFIRM_BALANCE_SELECT_ACCOUNT: 'ConfirmBalanceSelectAccountScreen',
  },
  OVER_DRAFT: {
    LIMIT_OFFER_SCREEN: 'LIMIT_OFFER_SCREEN',
    CONTRACT_DISPLAY: 'CONTRACT_DISPLAY',
    CREATION_SUCCESS: 'CREATION_SUCCESS',
    LOAN_LIST: 'LOAN_LIST',
    OD_DETAIL: 'OD_DETAIL',
    STATEMENT_LIST: 'OverdraftStatementListScreen',
    STATEMENT_DETAIL: 'OverdraftStatementDetailScreen',
    LIMIT_DETAIL: 'OverdraftLimitDetailScreen',
    CLOSE_ACCOUNT_CONFIRMATION: 'CloseAccountConfirmationScreen',
    CLOSE_ACCOUNT_SUCCESS: 'CloseAccountSuccessScreen',
    OD_PROCESSING_SCREEN: 'OverDraftInProcessingScreen',
  },
  HD_SAISON: {
    HD_SAISON_PRODUCT: 'HDSaisonProductScreen',
    HD_SAISON_CONSENT_OTP: 'HDSaisonConsentOTPScreen',
    HD_SAISON_APPROVED_SCREEN: 'HDSaisonApprovedScreen',
    HD_SAISON_WEBVIEW: 'HDSaisonWebViewScreen',
  },
  PHYSICAL_CARD: {
    PHYSICAL_CARD_REQUEST: 'RequestPhysicalCard',
    CARDS_CHANGE_ATM_PIN: 'CardChangeAtmPin',
    CARD_ACTIVATION_SCREEN: 'CardActivationScreen',
    CARD_DELIVERY_STATUS: 'CardActivationDetailsScreen',
    CARD_REQUEST_SUCCESS_SCREEN: 'CardRequestSuccessScreen',
    PHYSICAL_CARD_INTRO_SCREEN: 'PhysicalCardIntroScreen',
    PHYSICAL_CARD_CONFIRM_FEE_SCREEN: 'PhysicalCardConfirmFeeScreen',
    PHYSICAL_CARD_PAYMENT_RESULT: 'PhysicalCardPaymentResult',
  },
  HDI: {
    HDI_WEBVIEW: 'HDIWebviewScreen',
    HDI_INTRODUCTION: 'HDIProductIntroductionScreen',
    HDI_SHARE_INFO: 'HDIShareInformationScreen',
    HDI_CERTIFICATE: 'HDICertificateScreen',
    HDI_PRODUCT_LIST: 'TravelInsuranceProductList',
    HDI_PRODUCT_CATEGORY: 'TravelInsuranceCategoryList',
  },
  LUCKY_SPIN: {
    LUCKY_SPIN: 'LuckySpinScreen',
    GAIN_SPIN: 'GainSpinScreen',
    PRIZE_HISTORY: 'PrizeHistory',
  },
  PRETTY_ACCOUNT: {
    PRETTY_ACCOUNT: 'PrettyAccountScreen',
    REVIEW_NUMBER: 'ReviewNumberScreen',
    PRETTY_ACCOUNT_INTRO: 'PrettyAccountIntro',
    PURCHASE_SUCCESS: 'PurchaseSuccessScreen',
    CONFIRM_CUSTOMER_DETAIL: 'ConfirmCustomerDetailScreen',
  },
  VICTORIA_PREPAID: {
    ACTIVATION_SCREEN: 'VictoriaActivationScreen',
    CONFIRMATION_SCREEN: 'VictoriaConfirmationScreen',
    REPORT_SCREEN: 'VictoriaReportScreen',
  },
  FX_EXCHANGE: {
    INTRODUCTION: 'FxIntroductionScreen',
    CURRENCY_INPUT: 'FxCurrencyInputScreen',
    BRANCH_SELECT: 'FxBranchSelectScreen',
    BRANCH_MANUAL_SELECT: 'FxBranchManualSelectScreen',
    COLLECTION_DETAIL: 'ForeignCurrencyCollectionDetailScreen',
    EXCHANGE_HISTORY: 'ForeignCurrencyExchangeHistoryScreen',
    EXCHANGE_RESULT: 'ForeignCurrencyExchangeResultScreen',
    CONFIRMATION: 'FxConfirmationScreen',
  },
  ATM_WITHDRAWAL: {
    INPUT_WITHDRAWAL_AMOUNT: 'InputWithdrawalAmountScreen',
    WITHDRAWAL_CONFIRMATION: 'WithdrawalConfirmationScreen',
    WITHDRAWAL_VERIFICATION: 'WithdrawalVerificationScreen',
    WITHDRAWAL_PROCESSING: 'WithdrawalProcessingScreen',
    WITHDRAWAL_RESULT: 'WithdrawalResultScreen',
    WITHDRAWAL_INTRODUCTION: 'WithdrawalInstructionScreen',
  },
  FLIGHT_BOOKING: {
    CONFIRMATION: 'FlightBookingConfirmationScreen',
    PAYMENT_RESULT: 'FlightBookingPaymentResultScreen',
  },
  FAST_LOAN: {
    COLLECT_INFORMATION: 'CollectInformationScreen',
    FAST_LOAN_INTRODUCTION: 'FastLoanIntroduction',
    FAST_LOAN_APPLY_SUCCESS: 'FastLoanApplySuccessScreen',
  },
  PARTNER: {
    SSMEDIA_WEBVIEW: 'SSMediaWebViewScreen',
    SSMEDIA_PAYMENT_CONFIRM: 'SSMediaPaymentConfirmScreen',
    SSMEDIA_PAYMENT_RESULT: 'SSMediaPaymentResultScreen',
  },
  CARD_ONBOARDING: {
    CONSENT_OTP: 'CardConsentOtpScreen',
    TICKIE_CVP_SCREEN: 'TickieCardCVP',
    CARD_SELECT_TYPE: 'CardSelectTypeScreen',
    CARD_SCAN_NID: 'CardScanNIDScreen',
    NID_INFO_REVIEW: 'CardNIDInfoScreen',
    CARD_ADDRESS_SELECTION: 'CardAddressSelectScreen',
    CARD_SCAN_FACE: 'CardFaceScanScreen',
    COLLECT_PERSONAL_INFO: 'CollectPersonalInfoScreen',
    COLLECT_USER_REFERENT_INFO: 'CollectUserReferentInfo',
    CONTRACT_PREVIEW: 'CardContractPreviewScreen',
    CARD_VERIFY_NFC: 'CardNfcVerifyScreen',
    CARD_SKY_JOY_PROCESSING: 'CardSkyJoyProcessingScreen',
    SKY_JOY_CREDIT_CARD_INTRO: 'SkyJoyCreditCardIntroScreen',
    SKY_JOY_CARD_CVP: 'SkyJoyCardCvpScreen',
    SKY_JOY_DEBIT_CARD_INTRO: 'SkyJoyDebitIntroScreen',
  },
  ASEAN_QR: {
    INPUT_ASEAN_QR_AMOUNT: 'InputAseanQrAmountScreen',
    ASEAN_QR_RESULT_SCREEN: 'AseanQrResultScreen',
    ASEAN_QR_CONFIRMATION_SCREEN: 'AseanQrConfirmationScreen',
    ASEAN_QR_INSTRUCTION_SCREEN: 'AseanQrInstructionScreen',
  },
} as const;

export const PATH_TO_ROUTE_CONFIG: {
  [key: string]: {
    screenName: any;
    requireUserAuth: boolean;
  };
} = {
  register: {
    screenName: ROUTES.DASHBOARD.INTRO,
    requireUserAuth: false,
  },
  cards: {
    screenName: ROUTES.CARDS.CARDS_SCREEN,
    requireUserAuth: true,
  },
  lucky_spin: {
    screenName: ROUTES.LUCKY_SPIN.LUCKY_SPIN,
    requireUserAuth: false,
  },
  fxExchange: {
    screenName: ROUTES.FX_EXCHANGE.INTRODUCTION,
    requireUserAuth: true,
  },
  beauty_number: {
    screenName: ROUTES.DASHBOARD.INTRO,
    requireUserAuth: false,
  },
  vneid: {
    screenName: ROUTES.ONBOARD.FACE_REGISTRATION,
    requireUserAuth: false,
  },
} as const;

export const CommonScreenOptions: any = {
  fullScreenGestureEnabled: true,
  headerShown: false,
  animation: 'slide_from_right',
  animationDuration: 250,
  freezeOnBlur: true,
  gestureEnabled: false,
};
